CREATE TABLE `yourtoday`.`member` (
  `USER_KEY` BIGINT NOT NULL,
  `USER_ID` VARCHAR(80) NOT NULL,
  `USER_PASSWORD` VARCHAR(100) NOT NULL,
  `USER_NAME` VARCHAR(40) NOT NULL,
  `USER_NICK` VARCHAR(80) NOT NULL,
  `USER_BIRTH` VARCHAR(40) NOT NULL,
  `USER_EMAIL` VARCHAR(100) NOT NULL,
  `USER_PHONE` VARCHAR(40) NOT NULL,
  `USER_WDATE` DATETIME NOT NULL,
  PRIMARY KEY (`USER_KEY`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) VISIBLE,
  UNIQUE INDEX `USER_NICK_UNIQUE` (`USER_NICK` ASC) VISIBLE);
  
  SELECT * FROM MEMBER;
  
  CREATE TABLE `yourtoday`.`journal` (
  `NOTE_SEQ` BIGINT NOT NULL,
  `NOTE_TITLE` VARCHAR(400) NOT NULL,
  `NOTE_CONTENTS` VARCHAR(400) NOT NULL,
  `NOTE_FILENAME1` LONGBLOB NOT NULL,
  `NOTE_FILENAME2` LONGBLOB NOT NULL,
  `NOTE_FILENAME3` LONGBLOB NOT NULL,
  `NOTE_REGDATE` DATE NOT NULL,
  `NOTE_MODDATE` DATE NOT NULL,
  `NOTE_VIEW` CHAR(1) NOT NULL,
  `NOTE_DELYN` CHAR(1) NOT NULL,
  `journalcol` VARCHAR(45) NOT NULL,
  `journalcol1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NOTE_SEQ`));

  SELECT * FROM JOURNAL;
  
  CREATE TABLE `yourtoday`.`dday` (
  `DNOTE_SEQ` BIGINT NOT NULL,
  `DNOTE_TITLE` VARCHAR(400) NOT NULL,
  `DNOTE_CONTENTS` VARCHAR(400) NOT NULL,
  `DNOTE_REGDATE` DATE NOT NULL,
  `DNOTE_MODDATE` DATE NOT NULL,
  `DNOTE_DELYN` CHAR(1) NOT NULL,
  PRIMARY KEY (`DNOTE_SEQ`));
  
  
